### ISSUE TITLE
The master branch is not worked

### ISSUE THREAD

**Issue by esanle** [Drakemor/RedDress-PlantUML#1]
We should use a development branch.The project is cool bro, we really need this script.
<img width="891" alt="Screen Shot 2019-07-04 at 10 13 16 PM" src="https://user-images.githubusercontent.com/10616740/60672871-0ca03b80-9ea9-11e9-8224-c62fa0393681.png">

**Comment by esanle** [comment]
http://plantuml.com/zh/preprocessing 
search for `Migration notes`, the definelong not worked

I made a pull request 

https://github.com/Drakemor/RedDress-PlantUML/pull/2

**Comment by Drakemor** [comment]
I saw your pull request, thank you for the contribution. There is an issue with just simply replacing definelong with function - it does not work on older readers, like one used in this plugin: https://github.com/markushedvall/plantuml-viewer
which is really nice, cause it has live update. 

I will try to figure out how to cover both cases or maybe upgrade the plugin for atom, which is the actually correct way to go, as definelong is legacy. I didn't thought it isn't supported anymore - it should.

**Comment by esanle** [comment]
I have a idea that we can write a build tool to extend the plantuml language like [less](http://lesscss.org/)

**Comment by Drakemor** [comment]
I decided to merge the pull request - Initially I have written something like you mentioned to provide the support for older versions, but plantuml has since dropped the support for legacy preprocessor and I saw no further benefit in that. 

Thanks for the pull request and solving the issue.
