### ISSUE TITLE
Error found in diagram test

### ISSUE THREAD

**Issue by madaniel** [Drakemor/RedDress-PlantUML#7]
Hi,

I've used the code from the readme:

!define LIGHTORANGE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

And got this error (I'm using Visual Code with PlantUML extension.

Error found in diagram test
ERROR 
93 
This function does not have any !return directive. Declare it as a procedure instead ? 
Some diagram description contains errors 

Screenshot:
https://ibb.co/MZhW2dK

**Comment by Ducournl** [comment]
Hi,
Go to  👉 : https://github.com/Drakemor/RedDress-PlantUML/pull/5

**Comment by Drakemor** [comment]
Resolved

**Comment by madaniel** [comment]
Thanks !
